// nuxt-app/app/components/landing/Plans.vue
<script setup lang="ts">
import { Check } from 'lucide-vue-next'

const props = defineProps<{
  selectedId: 'week' | 'month' | 'year' | null
}>()

const emit = defineEmits<{
  (e: 'select', id: 'week' | 'month' | 'year'): void
}>()

const plans = [
  { id: 'week', name: '1 Week', price: 24, cadence: '/ week', note: '7 servings', features: ['Daily morning delivery', 'Cancel anytime'] },
  { id: 'month', name: '1 Month', price: 89, cadence: '/ month', note: '30 servings', popular: true, features: ['Daily morning delivery', 'Save 8%', 'Pause anytime'] },
  { id: 'year', name: '1 Year', price: 899, cadence: '/ year', note: '365 servings', features: ['Daily morning delivery', 'Save 18%', 'Pause anytime'] },
] as const
</script>

<template>
  <section id="plans" class="border-b border-border/60 bg-secondary/30">
    <div class="mx-auto max-w-6xl px-6 py-24">
      <div class="text-center">
        <p class="text-xs uppercase tracking-[0.25em] text-muted-foreground">Subscription</p>
        <h2 class="mt-4 text-3xl font-light tracking-tight text-foreground md:text-4xl">Choose your routine.</h2>
      </div>
      <div class="mt-16 grid gap-8 md:grid-cols-3">
        <div
          v-for="plan in plans"
          :key="plan.id"
          @click="emit('select', plan.id)"
          :class="[
            'relative cursor-pointer rounded-3xl border p-8 transition-all hover:border-primary/50',
            selectedId === plan.id ? 'border-primary ring-1 ring-primary bg-card' : 'border-border bg-background'
          ]"
        >
          <div v-if="plan.popular" class="absolute -top-3 right-8 rounded-full bg-foreground px-3 py-1 text-[10px] font-medium uppercase tracking-wider text-background">
            Most Popular
          </div>
          <h3 class="text-2xl font-light tracking-tight text-foreground">{{ plan.name }}</h3>
          <div class="mt-4 flex items-baseline gap-1">
            <span class="text-4xl font-light text-foreground">${{ plan.price }}</span>
            <span class="text-sm text-muted-foreground">{{ plan.cadence }}</span>
          </div>
          <p class="mt-2 text-xs text-muted-foreground">{{ plan.note }}</p>
          <ul class="mt-8 space-y-3">
            <li v-for="feature in plan.features" :key="feature" class="flex items-center gap-3 text-sm text-muted-foreground">
              <Check class="h-4 w-4 text-primary" />
              {{ feature }}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
</template>

// src/components/landing/plans.tsx
import { Check } from "lucide-react";

const plans = [
  {
    id: "week",
    name: "1 Week",
    tagline: "Try it out",
    price: 24,
    cadence: "/ week",
    note: "7 servings · billed once",
    features: ["Daily fresh delivery", "Cancel anytime", "Single household size"],
    highlighted: false,
  },
  {
    id: "month",
    name: "1 Month",
    tagline: "Most popular",
    price: 89,
    cadence: "/ month",
    note: "30 servings · save 8%",
    features: ["Daily fresh delivery", "Free recipe card weekly", "Pause anytime"],
    highlighted: true,
  },
  {
    id: "year",
    name: "1 Year",
    tagline: "Best value",
    price: 899,
    cadence: "/ year",
    note: "365 servings · save 18%",
    features: ["Daily fresh delivery", "Seasonal limited editions", "Priority support"],
    highlighted: false,
  },
] as const;

export function Plans({ onSubscribe }: { onSubscribe: (id: string) => void }) {
  return (
    <section id="plans" className="border-b border-border/60 bg-background">
      <div className="mx-auto max-w-6xl px-6 py-24">
        <div className="max-w-2xl">
          <p className="text-xs uppercase tracking-[0.25em] text-muted-foreground">Subscription</p>
          <h2 className="mt-4 text-3xl font-light tracking-tight text-foreground md:text-4xl">
            Three ways to keep your kitchen stocked.
          </h2>
        </div>
        <div className="mt-14 grid gap-6 md:grid-cols-3">
          {plans.map((p) => (
            <article
              key={p.id}
              className={`flex flex-col rounded-sm border p-8 transition-colors ${
                p.highlighted
                  ? "border-primary bg-primary text-primary-foreground"
                  : "border-border bg-card text-card-foreground"
              }`}
            >
              <p className={`text-xs uppercase tracking-[0.25em] ${p.highlighted ? "text-primary-foreground/70" : "text-muted-foreground"}`}>
                {p.tagline}
              </p>
              <h3 className="mt-3 text-2xl font-light tracking-tight">{p.name}</h3>
              <div className="mt-8 flex items-baseline gap-1">
                <span className="text-4xl font-light">${p.price}</span>
                <span className={`text-sm ${p.highlighted ? "text-primary-foreground/70" : "text-muted-foreground"}`}>
                  {p.cadence}
                </span>
              </div>
              <p className={`mt-2 text-xs ${p.highlighted ? "text-primary-foreground/70" : "text-muted-foreground"}`}>{p.note}</p>
              <ul className="mt-8 space-y-3 text-sm">
                {p.features.map((f) => (
                  <li key={f} className="flex items-start gap-2">
                    <Check className={`mt-0.5 h-4 w-4 shrink-0 ${p.highlighted ? "text-primary-foreground" : "text-primary"}`} />
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
              <button
                onClick={() => onSubscribe(p.id)}
                className={`mt-10 inline-flex h-11 items-center justify-center rounded-sm text-xs font-medium uppercase tracking-wider transition-colors ${
                  p.highlighted
                    ? "bg-primary-foreground text-primary hover:bg-primary-foreground/90"
                    : "bg-foreground text-background hover:bg-foreground/90"
                }`}
              >
                Add to cart
              </button>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
