// app/components/SiteFooter.vue
<template>
  <footer class="border-t border-border/60 bg-background">
    <div class="mx-auto max-w-6xl px-6 py-12">
      <div
        class="flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"
      >
        <div>
          <h3 class="text-lg font-semibold text-foreground">
            Spinach & Cheese Co.
          </h3>
          <p class="mt-1 text-sm text-muted-foreground">
            Baked fresh. Delivered daily.
          </p>
        </div>
        <nav
          class="flex flex-wrap gap-6 text-xs font-semibold uppercase tracking-wide text-muted-foreground md:gap-8"
        >
          <NuxtLink
            :to="{ path: '/', hash: '#plans' }"
            class="hover:text-foreground transition-colors"
            >Subscription</NuxtLink
          >
          <NuxtLink
            :to="{ path: '/', hash: '#how' }"
            class="hover:text-foreground transition-colors"
            >How it's made</NuxtLink
          >
          <NuxtLink
            :to="{ path: '/', hash: '#benefits' }"
            class="hover:text-foreground transition-colors"
            >Benefits</NuxtLink
          >
          <a href="#" class="hover:text-foreground transition-colors"
            >Support</a
          >
        </nav>
      </div>
      <div class="mt-8 border-t border-border/60 pt-8">
        <p class="text-xs text-muted-foreground">
          &copy; 2026 Spinach & Cheese Co. All rights reserved.
        </p>
      </div>
    </div>
  </footer>
</template>

// src/components/site-footer.tsx
export function SiteFooter() {
  return (
    <footer className="border-t border-border/60 bg-background">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="flex flex-col items-start justify-between gap-6 md:flex-row md:items-center">
          <div>
            <div className="text-sm font-semibold tracking-tight text-foreground">Spinach &amp; Cheese Co.</div>
            <p className="mt-1 text-xs text-muted-foreground">Baked fresh. Delivered daily.</p>
          </div>
          <nav className="flex flex-wrap gap-x-8 gap-y-2 text-xs uppercase tracking-wider text-muted-foreground">
            <a href="#plans" className="hover:text-foreground">Subscription</a>
            <a href="#how" className="hover:text-foreground">How it's made</a>
            <a href="#benefits" className="hover:text-foreground">Benefits</a>
            <a href="#" className="hover:text-foreground">Support</a>
          </nav>
        </div>
        <div className="mt-10 border-t border-border/60 pt-6 text-xs text-muted-foreground">
          © {new Date().getFullYear()} Spinach &amp; Cheese Co. All rights reserved.
        </div>
      </div>
    </footer>
  );
}
